
-- Seed 10 enterprise showcase templates into ad_reference_library
INSERT INTO ad_reference_library (title, description, media_type, media_url, thumbnail_url, industry_tags, mood_tags, platform_tags, compatible_families, sealcam_analysis, performance_notes) VALUES
('Fashion Editorial Campaign', 'High-end fashion editorial with dramatic lighting and model poses. Studio-quality visual storytelling.', 'image', 'https://images.unsplash.com/photo-1509631179647-0177331693ae?w=800&q=80', 'https://images.unsplash.com/photo-1509631179647-0177331693ae?w=400&q=80', '{fashion,apparel,luxury}', '{elegant,bold,editorial}', '{instagram,pinterest,tiktok}', '{F8_creative_cloner,F5_cinematic}', '{"composition":"rule_of_thirds","lighting":"dramatic_side","color_palette":"neutral_warm","mood":"editorial_confidence","focal_point":"model_center"}', 'High engagement on Instagram Reels. Best for TOF awareness.'),

('Luxury Skincare Collection', 'Premium skincare product arrangement with soft diffused lighting. Conveys trust and premium quality.', 'image', 'https://images.unsplash.com/photo-1556228578-0d85b1a4d571?w=800&q=80', 'https://images.unsplash.com/photo-1556228578-0d85b1a4d571?w=400&q=80', '{beauty,skincare,wellness}', '{luxurious,clean,minimal}', '{instagram,facebook,pinterest}', '{F8_creative_cloner,F9_image_template}', '{"composition":"centered_product","lighting":"soft_diffused","color_palette":"white_gold","mood":"premium_trust","focal_point":"product_array"}', 'Strong conversion on Facebook. Top performer for MOF retargeting.'),

('Minimal Sneaker Drop', 'Clean product showcase with minimal background. Focus on texture and design details.', 'image', 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=800&q=80', 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=400&q=80', '{ecommerce,footwear,streetwear}', '{minimal,bold,modern}', '{instagram,tiktok}', '{F8_creative_cloner,F9_image_template}', '{"composition":"floating_product","lighting":"studio_gradient","color_palette":"red_on_neutral","mood":"hype_drop","focal_point":"product_hero"}', 'Viral potential on TikTok. Best for product launch campaigns.'),

('Food & Beverage Hero Shot', 'Appetizing food photography with warm tones and natural styling. Triggers cravings instantly.', 'image', 'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=800&q=80', 'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=400&q=80', '{food,restaurant,beverage}', '{warm,appetizing,lifestyle}', '{instagram,facebook,tiktok}', '{F8_creative_cloner,F1_ugc}', '{"composition":"overhead_flat_lay","lighting":"natural_warm","color_palette":"warm_earth","mood":"crave_worthy","focal_point":"dish_center"}', 'Highest save rate among food ads. Perfect for local restaurant campaigns.'),

('Tech Product Ad — Smartwatch', 'Sleek technology product on dark background. Premium positioning with subtle reflections.', 'image', 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=800&q=80', 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=400&q=80', '{technology,gadgets,wearables}', '{sleek,futuristic,premium}', '{instagram,youtube,linkedin}', '{F8_creative_cloner,F5_cinematic}', '{"composition":"centered_hero","lighting":"rim_light_dark","color_palette":"dark_tech","mood":"innovation","focal_point":"product_face"}', 'Strong CTR on YouTube pre-roll. Best for tech-savvy audience TOF.'),

('Luxury Real Estate', 'Stunning property interior with natural light flooding through large windows. Aspirational living.', 'image', 'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800&q=80', 'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=400&q=80', '{real_estate,property,luxury}', '{aspirational,elegant,spacious}', '{instagram,facebook,linkedin}', '{F8_creative_cloner,F5_cinematic}', '{"composition":"wide_interior","lighting":"natural_flood","color_palette":"white_wood_warm","mood":"dream_home","focal_point":"living_space"}', 'Top performer for real estate lead gen on Facebook.'),

('Fitness Energy Brand', 'Dynamic fitness photography capturing motion and energy. Inspires action and transformation.', 'image', 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=800&q=80', 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=400&q=80', '{fitness,health,wellness}', '{energetic,powerful,motivational}', '{instagram,tiktok,youtube}', '{F8_creative_cloner,F1_ugc}', '{"composition":"action_shot","lighting":"dramatic_gym","color_palette":"dark_orange_accent","mood":"grind_energy","focal_point":"athlete_motion"}', 'High share rate on TikTok. Best for fitness supplement and gym campaigns.'),

('Coffee Lifestyle Brand', 'Cozy lifestyle coffee moment with warm tones and natural textures. Relatable daily ritual.', 'image', 'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=800&q=80', 'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=400&q=80', '{lifestyle,coffee,cafe}', '{cozy,warm,relatable}', '{instagram,pinterest,tiktok}', '{F8_creative_cloner,F1_ugc}', '{"composition":"close_up_hands","lighting":"soft_natural","color_palette":"brown_cream","mood":"morning_ritual","focal_point":"cup_hands"}', 'Highest engagement on Pinterest. Perfect for DTC coffee and lifestyle brands.'),

('Luxury Jewelry — Gold Collection', 'Exquisite gold jewelry on dark velvet. Maximum sparkle and perceived value.', 'image', 'https://images.unsplash.com/photo-1515562141589-67f0d999aee6?w=800&q=80', 'https://images.unsplash.com/photo-1515562141589-67f0d999aee6?w=400&q=80', '{jewelry,luxury,fashion}', '{luxurious,elegant,sparkling}', '{instagram,pinterest,facebook}', '{F8_creative_cloner,F9_image_template}', '{"composition":"macro_detail","lighting":"spot_highlight","color_palette":"gold_on_dark","mood":"opulent","focal_point":"gemstone_center"}', 'Strongest ROAS for jewelry brands on Instagram Shopping.'),

('Travel & Tourism — Tropical Paradise', 'Breathtaking tropical destination with turquoise waters. Triggers wanderlust and booking intent.', 'image', 'https://images.unsplash.com/photo-1506929562872-bb421503ef21?w=800&q=80', 'https://images.unsplash.com/photo-1506929562872-bb421503ef21?w=400&q=80', '{travel,tourism,hospitality}', '{dreamy,adventurous,serene}', '{instagram,facebook,tiktok}', '{F8_creative_cloner,F5_cinematic}', '{"composition":"wide_landscape","lighting":"golden_hour","color_palette":"turquoise_sand","mood":"wanderlust","focal_point":"horizon_water"}', 'Drives direct bookings on Facebook. Best for travel agency TOF campaigns.');
