
-- ═══════════════════════════════════════════════════════════
-- SEED: video_templates (15 entries)
-- Uses only allowed families: F1_UGC, F2_SPOKESPERSON, F5_CINEMATIC
-- ═══════════════════════════════════════════════════════════
INSERT INTO public.video_templates (template_name, family, aspect_ratio, duration_s, mood, hook_type, tags, sealcam_analysis) VALUES
('UGC Talking Head – Testimonial', 'F1_UGC', '9:16', 15, 'authentic', 'story', '{ugc,testimonial,talking_head,mobile}', '{"subject":"person speaking to camera","environment":"casual home/office","action":"direct address testimonial","lighting":"natural window light","camera":"static medium close-up","mood":"authentic trust"}'),
('UGC Problem-Solution Demo', 'F1_UGC', '9:16', 30, 'energetic', 'question', '{ugc,demo,problem_solution,mobile}', '{"subject":"person demonstrating product","environment":"real-world setting","action":"show problem then reveal solution","lighting":"bright natural","camera":"handheld dynamic","mood":"relatable excitement"}'),
('UGC Before/After Reveal', 'F1_UGC', '9:16', 15, 'dramatic', 'bold_claim', '{ugc,before_after,transformation,mobile}', '{"subject":"transformation sequence","environment":"split-screen or transition","action":"dramatic before-after reveal","lighting":"contrasting warm/cool","camera":"static with whip pan transition","mood":"dramatic impact"}'),
('UGC Unboxing Experience', 'F1_UGC', '9:16', 30, 'excited', 'curiosity', '{ugc,unboxing,first_impression,mobile}', '{"subject":"person unboxing product","environment":"home setting desk/counter","action":"genuine unboxing reaction","lighting":"bright natural","camera":"POV close-up hands","mood":"excited discovery"}'),
('UGC Day-in-Life Integration', 'F1_UGC', '9:16', 15, 'authentic', 'story', '{ugc,lifestyle,routine,mobile}', '{"subject":"person in daily routine","environment":"real home/office/gym","action":"natural product use in routine","lighting":"natural ambient","camera":"handheld vlog style","mood":"relatable authenticity"}'),
('Spokesperson Authority Pitch', 'F2_SPOKESPERSON', '9:16', 30, 'professional', 'statistic', '{spokesperson,authority,professional,mobile}', '{"subject":"professional spokesperson","environment":"clean studio backdrop","action":"authoritative product endorsement","lighting":"three-point studio","camera":"medium shot with subtle zoom","mood":"credible authority"}'),
('Spokesperson Casual Recommend', 'F2_SPOKESPERSON', '9:16', 15, 'warm', 'story', '{spokesperson,casual,recommendation,mobile}', '{"subject":"relatable spokesperson","environment":"lifestyle setting","action":"casual product recommendation","lighting":"soft natural","camera":"medium close-up handheld","mood":"friendly warmth"}'),
('Spokesperson Expert Breakdown', 'F2_SPOKESPERSON', '16:9', 30, 'educational', 'question', '{spokesperson,expert,educational,desktop}', '{"subject":"expert spokesperson with graphics","environment":"modern office with screen overlay","action":"data-backed product explanation","lighting":"bright even studio","camera":"medium wide with B-roll cuts","mood":"educational credibility"}'),
('Spokesperson Lifestyle Endorsement', 'F2_SPOKESPERSON', '9:16', 15, 'aspirational', 'bold_claim', '{spokesperson,lifestyle,endorsement,mobile}', '{"subject":"spokesperson in lifestyle context","environment":"premium lifestyle location","action":"natural endorsement while living","lighting":"golden hour","camera":"cinematic handheld","mood":"aspirational warmth"}'),
('Spokesperson Direct Response', 'F2_SPOKESPERSON', '9:16', 30, 'urgent', 'statistic', '{spokesperson,direct_response,conversion,mobile}', '{"subject":"spokesperson with offer overlay","environment":"clean branded backdrop","action":"clear pitch with CTA","lighting":"bright commercial","camera":"static with text overlays","mood":"urgent action"}'),
('Cinematic Brand Story', 'F5_CINEMATIC', '16:9', 30, 'epic', 'story', '{cinematic,brand_story,epic,desktop}', '{"subject":"brand narrative sequence","environment":"multiple cinematic locations","action":"emotional storytelling arc","lighting":"cinematic color graded","camera":"crane and steadicam movements","mood":"epic inspiration"}'),
('Cinematic Product Launch', 'F5_CINEMATIC', '16:9', 15, 'dramatic', 'bold_claim', '{cinematic,launch,dramatic,desktop}', '{"subject":"product hero moment","environment":"abstract or dramatic backdrop","action":"dynamic reveal with motion graphics","lighting":"high contrast dramatic","camera":"macro to wide pull-out","mood":"launch excitement"}'),
('Cinematic Luxury Reveal', 'F5_CINEMATIC', '16:9', 15, 'luxurious', 'curiosity', '{cinematic,luxury,reveal,desktop}', '{"subject":"product on pedestal","environment":"dark studio with accent lighting","action":"slow rotation reveal with particle effects","lighting":"dramatic rim light","camera":"orbiting dolly shot","mood":"premium desire"}'),
('Cinematic Lifestyle Film', 'F5_CINEMATIC', '16:9', 30, 'aspirational', 'story', '{cinematic,lifestyle,aspirational,desktop}', '{"subject":"people living with product","environment":"aspirational lifestyle locations","action":"seamless product integration into life","lighting":"golden hour warm","camera":"cinematic tracking shot","mood":"aspirational lifestyle"}'),
('Cinematic Mini-Doc', 'F5_CINEMATIC', '16:9', 30, 'inspirational', 'story', '{cinematic,documentary,brand_building,desktop}', '{"subject":"founder or customer journey","environment":"real locations with cinematic treatment","action":"documentary-style narrative","lighting":"natural with cinematic grade","camera":"interview setups with B-roll","mood":"inspirational authenticity"}');

-- ═══════════════════════════════════════════════════════════
-- SEED: character_library (12 entries)
-- ═══════════════════════════════════════════════════════════
INSERT INTO public.character_library (name, description, gender, age_range, voice_style, persona_traits, industry_tags, mood_tags, compatible_families, ethnicity_tags) VALUES
('Dr. Sarah Chen', 'Authoritative health & wellness expert with warm bedside manner', 'female', '35-45', 'professional', '{"archetype":"expert","tone":"warm authority","energy":"calm confidence"}', '{health,wellness,medspa,skincare,fitness}', '{professional,warm,trustworthy}', '{F2_SPOKESPERSON,F1_UGC}', '{asian}'),
('Marcus Johnson', 'Charismatic tech reviewer with infectious enthusiasm', 'male', '25-35', 'energetic', '{"archetype":"enthusiast","tone":"excited discovery","energy":"high"}', '{technology,gadgets,saas,gaming}', '{energetic,excited,playful}', '{F2_SPOKESPERSON,F1_UGC}', '{black}'),
('Emma Rodriguez', 'Relatable lifestyle creator with authentic girl-next-door energy', 'female', '22-30', 'casual', '{"archetype":"friend","tone":"casual authentic","energy":"medium"}', '{fashion,beauty,lifestyle,food,travel}', '{authentic,warm,relatable}', '{F1_UGC,F2_SPOKESPERSON}', '{hispanic}'),
('James Sullivan', 'Distinguished executive presence for B2B and finance', 'male', '45-55', 'authoritative', '{"archetype":"leader","tone":"executive authority","energy":"measured"}', '{finance,real_estate,legal,consulting,b2b}', '{professional,authoritative,trustworthy}', '{F2_SPOKESPERSON,F5_CINEMATIC}', '{caucasian}'),
('Priya Sharma', 'Vibrant beauty and fashion influencer with trend expertise', 'female', '25-32', 'trendy', '{"archetype":"trendsetter","tone":"excited discovery","energy":"high"}', '{beauty,fashion,skincare,cosmetics}', '{trendy,excited,luxurious}', '{F1_UGC,F2_SPOKESPERSON}', '{south_asian}'),
('David Kim', 'Calm fitness coach with motivational presence', 'male', '28-38', 'motivational', '{"archetype":"coach","tone":"motivational calm","energy":"focused"}', '{fitness,sports,nutrition,wellness,supplements}', '{motivational,calm,focused}', '{F2_SPOKESPERSON,F1_UGC}', '{asian}'),
('Olivia Bennett', 'Sophisticated luxury brand ambassador', 'female', '30-40', 'elegant', '{"archetype":"ambassador","tone":"refined elegance","energy":"poised"}', '{luxury,jewelry,watches,automotive,wine}', '{luxurious,elegant,aspirational}', '{F2_SPOKESPERSON,F5_CINEMATIC}', '{caucasian}'),
('Carlos Rivera', 'High-energy food and hospitality enthusiast', 'male', '30-40', 'passionate', '{"archetype":"connoisseur","tone":"passionate storyteller","energy":"high"}', '{food,restaurant,hospitality,beverage,cooking}', '{passionate,warm,energetic}', '{F1_UGC,F2_SPOKESPERSON}', '{hispanic}'),
('Aisha Okafor', 'Empowering education and personal development mentor', 'female', '32-42', 'inspiring', '{"archetype":"mentor","tone":"empowering guide","energy":"steady"}', '{education,coaching,self_help,career,courses}', '{inspiring,warm,empowering}', '{F2_SPOKESPERSON,F1_UGC}', '{black}'),
('Ryan Mitchell', 'Adventurous outdoor and lifestyle brand voice', 'male', '25-35', 'adventurous', '{"archetype":"explorer","tone":"excited discovery","energy":"high"}', '{outdoor,travel,automotive,sports,adventure}', '{adventurous,energetic,authentic}', '{F1_UGC,F2_SPOKESPERSON}', '{caucasian}'),
('Mei Lin', 'Minimalist design and home aesthetics specialist', 'female', '28-38', 'calm', '{"archetype":"curator","tone":"thoughtful minimalism","energy":"calm"}', '{home_decor,design,architecture,furniture,art}', '{calm,minimal,elegant}', '{F2_SPOKESPERSON,F1_UGC}', '{asian}'),
('Alex Morgan', 'Gender-neutral tech-forward startup voice', 'neutral', '25-35', 'conversational', '{"archetype":"innovator","tone":"casual smart","energy":"medium"}', '{saas,startup,fintech,crypto,ai}', '{modern,smart,approachable}', '{F1_UGC,F2_SPOKESPERSON}', '{mixed}');

-- ═══════════════════════════════════════════════════════════
-- SEED: hooks (20 entries)
-- ═══════════════════════════════════════════════════════════
INSERT INTO public.hooks (hook_text, hook_type, platform, family, effectiveness_score) VALUES
('Stop scrolling if you''ve ever struggled with {pain_point}', 'bold_claim', 'instagram_reels', 'F1_UGC', 0.85),
('I tested {product} for 30 days — here''s what happened', 'story', 'tiktok', 'F1_UGC', 0.82),
('Did you know {statistic}? Most people don''t.', 'statistic', 'instagram_reels', 'F2_SPOKESPERSON', 0.78),
('The #1 mistake {audience} make with {topic}', 'question', 'tiktok', 'F1_UGC', 0.88),
('POV: You just discovered the secret to {benefit}', 'curiosity', 'tiktok', 'F1_UGC', 0.80),
('This changed everything about how I {action}', 'story', 'instagram_reels', 'F1_UGC', 0.83),
('{Industry} experts don''t want you to know this', 'curiosity', 'tiktok', 'F2_SPOKESPERSON', 0.76),
('Here''s why {number}% of {audience} are switching to {solution}', 'statistic', 'youtube_shorts', 'F2_SPOKESPERSON', 0.81),
('I was today years old when I learned {insight}', 'story', 'tiktok', NULL, 0.74),
('Wait for the before and after — you won''t believe this', 'curiosity', 'instagram_reels', 'F1_UGC', 0.86),
('If you''re still using {old_solution}, watch this', 'bold_claim', 'tiktok', 'F1_UGC', 0.79),
('3 things I wish I knew before {action}', 'question', 'instagram_reels', NULL, 0.77),
('This {product_category} literally saved my {outcome}', 'story', 'tiktok', 'F1_UGC', 0.84),
('Your {competitor} doesn''t want you to see this', 'curiosity', 'youtube_shorts', NULL, 0.75),
('Warning: This will change how you think about {topic}', 'bold_claim', 'instagram_reels', 'F2_SPOKESPERSON', 0.80),
('Ready to transform your {area} in just {timeframe}?', 'question', 'facebook', NULL, 0.73),
('The truth about {topic} that nobody talks about', 'curiosity', 'youtube_shorts', 'F5_CINEMATIC', 0.78),
('I''ve helped {number}+ {audience} achieve {result} — here''s how', 'statistic', 'instagram_reels', 'F2_SPOKESPERSON', 0.82),
('Unpopular opinion: {contrarian_take}', 'bold_claim', 'tiktok', NULL, 0.76),
('What would you do with {benefit}?', 'question', 'facebook', NULL, 0.71);

-- ═══════════════════════════════════════════════════════════
-- SEED: image_templates (10 entries)
-- ═══════════════════════════════════════════════════════════
INSERT INTO public.image_templates (style_name, vertical, quality_tier, platform, format, prompt_modifiers, negative_prompt, style_guide, tags) VALUES
('Clean Product Hero', 'ecommerce', 'premium', 'instagram', '1:1', '{product photography,studio lighting,clean white background,high detail,commercial quality}', 'blurry, low quality, distorted, watermark, text overlay, amateur, cluttered background', '{"lighting":"soft studio three-point","background":"clean white or light gradient","composition":"centered product hero","color_treatment":"true to life with slight saturation boost"}', '{product,hero,clean,ecommerce}'),
('Lifestyle Product Integration', 'lifestyle', 'standard', 'instagram', '4:5', '{lifestyle photography,natural setting,product in use,warm tones,aspirational}', 'blurry, staged, fake, stock photo feel, watermark, text overlay', '{"lighting":"golden hour or natural window","background":"real lifestyle environment","composition":"product naturally integrated","color_treatment":"warm film-like tones"}', '{lifestyle,warm,aspirational,product_in_use}'),
('Dark Luxury Showcase', 'luxury', 'premium', 'instagram', '1:1', '{luxury product photography,dark moody,dramatic lighting,premium feel,high contrast}', 'cheap looking, bright, flat lighting, amateur, cluttered', '{"lighting":"dramatic single key with rim light","background":"dark gradient or textured surface","composition":"elegant minimal with negative space","color_treatment":"rich shadows with metallic highlights"}', '{luxury,dark,dramatic,premium}'),
('Minimal Editorial', 'fashion', 'standard', 'instagram', '4:5', '{editorial fashion,minimal composition,muted tones,magazine quality,sophisticated}', 'busy background, oversaturated, amateur, cluttered, text overlay', '{"lighting":"soft diffused editorial","background":"minimal neutral tones","composition":"fashion editorial with breathing room","color_treatment":"desaturated with selective color"}', '{editorial,minimal,fashion,sophisticated}'),
('Bold Social Card', 'general', 'standard', 'instagram', '1:1', '{social media graphic,bold typography,brand colors,eye-catching,modern design}', 'blurry, low contrast, hard to read, cluttered, old-fashioned', '{"lighting":"flat graphic style","background":"solid or gradient brand colors","composition":"text-forward with supporting imagery","color_treatment":"high contrast brand palette"}', '{social,graphic,bold,text_forward}'),
('Food & Beverage Hero', 'food', 'premium', 'instagram', '1:1', '{food photography,appetizing,fresh ingredients,warm lighting,top-down or 45-degree}', 'unappetizing, cold lighting, messy, artificial, plastic looking', '{"lighting":"warm directional with fill","background":"natural textures wood/marble","composition":"top-down or 45-degree hero","color_treatment":"warm saturated appetite appeal"}', '{food,appetizing,warm,restaurant}'),
('Real Estate Showcase', 'real_estate', 'standard', 'facebook', '16:9', '{real estate photography,wide angle,bright airy,HDR-like,welcoming}', 'dark, cramped, fisheye distortion, messy, cluttered', '{"lighting":"bright balanced HDR-style","background":"property interior or exterior","composition":"wide angle showcasing space","color_treatment":"bright airy with enhanced windows"}', '{real_estate,property,bright,spacious}'),
('Fitness Motivation', 'fitness', 'standard', 'instagram', '4:5', '{fitness photography,dynamic action,high energy,dramatic lighting,motivational}', 'static, boring, flat, unfocused, cluttered', '{"lighting":"dramatic gym or outdoor lighting","background":"gym environment or outdoor","composition":"dynamic action pose","color_treatment":"high contrast with warm skin tones"}', '{fitness,dynamic,motivational,action}'),
('Tech Product Render', 'technology', 'premium', 'instagram', '1:1', '{tech product,clean render,futuristic,sleek,gradient background}', 'blurry, old technology, cheap, plastic, cluttered', '{"lighting":"clean soft with colored rim lights","background":"subtle gradient or abstract tech","composition":"floating product with subtle shadow","color_treatment":"cool tones with neon accents"}', '{tech,sleek,futuristic,product}'),
('Beauty & Skincare Glow', 'beauty', 'premium', 'instagram', '4:5', '{beauty photography,glowing skin,soft focus,dewy,premium cosmetics}', 'harsh, unflattering, dry skin, amateur, clinical', '{"lighting":"soft beauty dish with fill","background":"clean tonal or gradient","composition":"close-up with product placement","color_treatment":"soft glow with skin-flattering warmth"}', '{beauty,skincare,glow,premium}');

-- ═══════════════════════════════════════════════════════════
-- SEED: ad_reference_library (10 entries)
-- ═══════════════════════════════════════════════════════════
INSERT INTO public.ad_reference_library (title, description, media_type, compatible_families, industry_tags, mood_tags, platform_tags, sealcam_analysis) VALUES
('Fast-Cut Product Montage', 'High-energy rapid cuts showcasing product from multiple angles with dynamic transitions', 'video', '{F8_creative_cloner}', '{ecommerce,fashion,beauty}', '{energetic,dynamic,urgent}', '{tiktok,instagram_reels}', '{"scenes":[{"subject":"product close-up","action":"rapid angle change","camera":"quick cuts","duration_s":2},{"subject":"product in use","action":"fast montage","camera":"handheld dynamic","duration_s":3}],"pacing":"fast","total_duration_s":15}'),
('Luxury Slow Reveal', 'Elegant slow-motion product reveal with premium lighting and minimal composition', 'video', '{F8_creative_cloner,F5_cinematic}', '{luxury,jewelry,watches,automotive}', '{luxurious,elegant,dramatic}', '{youtube_ads,instagram_reels}', '{"scenes":[{"subject":"dark silhouette","action":"slow light reveal","camera":"smooth dolly","duration_s":5},{"subject":"product detail","action":"macro exploration","camera":"slow orbit","duration_s":5}],"pacing":"slow","total_duration_s":15}'),
('UGC Reaction Style', 'Authentic reaction-style ad showing genuine surprise and delight with product', 'video', '{F8_creative_cloner}', '{beauty,skincare,food,gadgets}', '{authentic,surprised,warm}', '{tiktok,instagram_reels}', '{"scenes":[{"subject":"person opening package","action":"genuine reaction","camera":"selfie cam","duration_s":5},{"subject":"product demo","action":"excited showcase","camera":"handheld close","duration_s":5}],"pacing":"medium","total_duration_s":15}'),
('Split-Screen Comparison', 'Side-by-side comparison format showing your product vs alternatives', 'image', '{F7_ad_creator}', '{saas,technology,beauty,supplements}', '{confident,analytical,bold}', '{facebook,instagram}', '{"layout":"split_screen","left":"competitor/old way","right":"your product/new way","emphasis":"contrast and clarity"}'),
('Testimonial Quote Card', 'Clean testimonial layout with customer quote, photo, and star rating', 'image', '{F7_ad_creator}', '{general,saas,ecommerce,services}', '{trustworthy,warm,professional}', '{facebook,instagram,linkedin}', '{"layout":"quote_card","elements":["customer_photo","quote_text","star_rating","brand_logo"],"style":"clean minimal with social proof emphasis"}'),
('Story-Driven Brand Film', 'Cinematic narrative arc with emotional storytelling and brand integration', 'video', '{F5_cinematic}', '{lifestyle,automotive,luxury,nonprofit}', '{inspirational,emotional,epic}', '{youtube_ads,facebook}', '{"scenes":[{"subject":"establishing shot","action":"set emotional tone","camera":"wide cinematic","duration_s":5},{"subject":"character journey","action":"narrative progression","camera":"tracking shots","duration_s":15},{"subject":"brand reveal","action":"emotional payoff","camera":"slow push-in","duration_s":5}],"pacing":"cinematic","total_duration_s":30}'),
('Problem-Agitate-Solve Ad', 'Classic direct response structure showing pain point, amplifying it, then presenting solution', 'video', '{F8_creative_cloner}', '{health,fitness,finance,saas,supplements}', '{urgent,empathetic,confident}', '{facebook,youtube_ads,instagram_reels}', '{"scenes":[{"subject":"pain point visualization","action":"show frustration","camera":"close-up emotion","duration_s":5},{"subject":"agitation","action":"amplify problem","camera":"dramatic angles","duration_s":5},{"subject":"solution reveal","action":"product as hero","camera":"bright confident","duration_s":5}],"pacing":"building","total_duration_s":15}'),
('Carousel Education Post', 'Multi-slide educational content with branded design system', 'image', '{F4_social_content}', '{education,coaching,saas,marketing}', '{informative,professional,engaging}', '{instagram,linkedin}', '{"layout":"carousel","slides":["hook_slide","insight_1","insight_2","insight_3","cta_slide"],"style":"consistent brand template with progressive disclosure"}'),
('Influencer Unboxing', 'Authentic unboxing experience with genuine first impressions', 'video', '{F8_creative_cloner}', '{ecommerce,beauty,gadgets,fashion,food}', '{excited,authentic,curious}', '{tiktok,youtube_shorts,instagram_reels}', '{"scenes":[{"subject":"sealed package","action":"build anticipation","camera":"close-up hands","duration_s":5},{"subject":"unboxing reveal","action":"genuine reaction","camera":"POV selfie","duration_s":5},{"subject":"first use","action":"authentic testing","camera":"handheld close","duration_s":5}],"pacing":"building","total_duration_s":15}'),
('Bold Statistic Ad', 'Data-driven ad leading with a compelling statistic and social proof', 'image', '{F7_ad_creator}', '{finance,health,saas,education,fitness}', '{bold,confident,analytical}', '{facebook,linkedin,instagram}', '{"layout":"stat_hero","elements":["large_number","context_text","product_image","cta_button"],"style":"bold typography with data visualization accent"}');
