// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bojqkxdpruyiblrdhelg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJvanFreGRwcnV5aWJscmRoZWxnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzQ3NTE0NzQsImV4cCI6MjA5MDMyNzQ3NH0.S88V-7A7u1xsVm2MBwVsnqvTwk6m5BFX5j2DJF8hBE0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});